
services:
  http:
    image: ghcr.io/credibil-grid/runtime:latest
    env_file: .env
    ports:
      - 8080:8080
    command: ["/http.wasm"]
    volumes:
       - ./target/wasm32-wasip2/release/http.wasm:/http.wasm
