name: Publish Release

on:
  workflow_dispatch:
    inputs:
      binary: 
        description: 'Binary to publish'
        default: 'standard'

jobs:
  ci:
    name: CI
    uses: credibil/pipeline/.github/workflows/ci.yaml@main

  publish:
    name: Publish
    needs: ci
    uses: credibil/pipeline/.github/workflows/publish.yaml@main

  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: publish
    
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: $${{ inputs.binary == 'standard' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            BINARY=${{ inputs.binary }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.publish.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Build and push image
        if: $${{ inputs.binary != 'standard' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            BINARY=${{ inputs.binary }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.binary }}-${{ needs.publish.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.binary }}-latest