name: Publish Release

on:
  workflow_dispatch:
    inputs:
      binary: 
        description: Binary to publish
        default: standard

jobs:
  tag:
    name: Tag release
    if: ${{ startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.cargo.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set git identity
        uses: credibil/pipeline/.github/actions/git-identity@main

      # - name: Get latest release
      #   id: latest
      #   uses: credibil/pipeline/.github/actions/latest-release@main

      - name: Cargo version
        id: cargo
        uses: credibil/pipeline/.github/actions/cargo-version@main
        
      - name: Update release notes
        run: |
          set -ex
          sed -i "s/^Unreleased/Released $(date +'%Y-%m-%d')/" RELEASES.md
          git commit --allow-empty -am "Release ${{ steps.cargo.outputs.version }}"
          git push

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.cargo.outputs.version }}
          
  # ci:
  #   name: CI
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # package:
  #   name: Package
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
    
  #   steps:
  #     - uses: docker/setup-qemu-action@v3
  #     - uses: docker/setup-buildx-action@v3

  #     - name: Log in to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: https://ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push image
  #       if: $${{ inputs.binary == 'standard' }}
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         build-args: |
  #           BINARY=${{ inputs.binary }}
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.publish.outputs.version }}
  #           ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

  #     - name: Build and push image
  #       if: $${{ inputs.binary != 'standard' }}
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         build-args: |
  #           BINARY=${{ inputs.binary }}
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.binary }}-${{ needs.publish.outputs.version }}
  #           ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.binary }}-latest